### ISSUE TITLE
Update README.md to include instructions for pulling jars from GH Packages

### ISSUE THREAD

**Issue by awkshwayrd** [xebia-os/spring-boot-react-maven-starter#19]
This should go in the README so people don't go hunting over the Internet to build the skeleton with the ArchUnit dependency locally. Or worse, comment it out altogether.

**Comment by shekhargulati** [comment]
I agree it turned out to be more complex than I expected. I had never used Github maven packages before this. I was expecting it to be straight forward. I think we can write a blog on it ;-)
